apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nome-do-servico-exemplo
  description: Descrição do serviço exemplo.
  tags:
    - java
    - backend
spec:
  type: service
  lifecycle: production
  owner: equipe-responsavel

links:
  - url: https://github.com/sua-organizacao/repositorio-servico
    title: Código Fonte
  - url: https://sua-organizacao.servico-exemplo/docs
    title: Documentação
